version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PYTHON_SERVICE_URL=http://localhost:8000
      - FRONTEND_URL=http://localhost:3001
      - CACHE_TTL=300
      - CACHE_MAX_ITEMS=100
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    # depends_on:
    #   - python-service
    networks:
      - geo-processor-network

  # python-service:
  #   image: python-geo-processor:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ENVIRONMENT=development
  #   networks:
  #     - geo-processor-network
  #   # Uncomment if you have the Python service built
  #   # build:
  #   #   context: ../geo-processor-python
  #   #   dockerfile: Dockerfile

networks:
  geo-processor-network:
    driver: bridge

volumes:
  node_modules:
